#!/bin/bash
# ============================================================
# Copy the runtime assets claw-core needs from a HundredBlockDash checkout:
# three.js, cannon.js and Trystero, the fonts, the minigame stylesheet and the
# biome colours. The core itself is the src/claw-core submodule
# (github.com/Claws02/claw-core) and is NOT touched here. Everything this
# script writes is gitignored.
#
# usage: bash scripts/sync-assets.sh ../HundredBlockDash
# ============================================================
set -euo pipefail
HBD="$(cd "${1:?path to HundredBlockDash checkout}" && pwd)"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
[ -f "$HBD/vendor/three.min.js" ] || { echo "$HBD does not look like a HundredBlockDash checkout"; exit 1; }
[ -f "$ROOT/src/claw-core/minigames/MinigameManager.js" ] || \
    echo "note: src/claw-core is empty; run: git submodule update --init"

mkdir -p "$ROOT/vendor" "$ROOT/assets/fonts"
cp "$HBD/vendor/three.min.js" "$HBD/vendor/cannon.min.js" "$ROOT/vendor/"
# Trystero (MIT): WebRTC signaling for Play Together, loaded only when a room opens.
cp "$HBD"/vendor/trystero-*.min.js "$HBD/vendor/TRYSTERO-LICENSE" "$ROOT/vendor/"
cp "$HBD"/assets/fonts/* "$ROOT/assets/fonts/"
# The minigame overlays are styled by HBD's sheet. Temporary: the minigame
# rules move into claw-core/ui/minigame.css and this copy goes away.
cp "$HBD/css/styles.css" "$ROOT/css/core-minigame.css"

# Stage sets read colours from HBD's biome tables, which also carry board copy,
# so they stay in HBD's config. Snapshot just the data the stages need.
NODE_NO_WARNINGS=1 node --input-type=module -e "
import { DISTRICT_BIOMES, HBD_BIOMES } from '$HBD/src/config/GameConfig.js';
const fs = await import('fs');
fs.writeFileSync('$ROOT/src/host/biomes.js',
  '// GENERATED by scripts/sync-assets.sh from HundredBlockDash GameConfig. Do not edit.\n' +
  'export const DISTRICT_BIOMES = ' + JSON.stringify(DISTRICT_BIOMES) + ';\n' +
  'export const HBD_BIOMES = ' + JSON.stringify(HBD_BIOMES) + ';\n');
"
echo "synced assets from $HBD ($(cd "$HBD" && git rev-parse --short HEAD)); claw-core is at $(git -C "$ROOT/src/claw-core" rev-parse --short HEAD 2>/dev/null || echo '(not initialised)')"
