#!/bin/bash
# ============================================================
# Pull the shared minigame core and its runtime assets in from a
# HundredBlockDash checkout. Stopgap until claw-core is its own repo and
# lands here as a git submodule at src/claw-core/ — everything this script
# writes is gitignored for that reason.
#
# usage: bash scripts/sync-core.sh ../HundredBlockDash
# ============================================================
set -euo pipefail
HBD="$(cd "${1:?path to HundredBlockDash checkout}" && pwd)"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
[ -d "$HBD/src/claw-core" ] || { echo "no src/claw-core in $HBD (wrong branch?)"; exit 1; }

rm -rf "$ROOT/src/claw-core"
mkdir -p "$ROOT/src/claw-core" "$ROOT/vendor" "$ROOT/assets/fonts"
# Archived games have stale imports and never ship.
cp -R "$HBD/src/claw-core/." "$ROOT/src/claw-core/"
rm -rf "$ROOT/src/claw-core/minigames/archived"
cp "$HBD/vendor/three.min.js" "$HBD/vendor/cannon.min.js" "$ROOT/vendor/"
cp "$HBD"/assets/fonts/* "$ROOT/assets/fonts/"
# The minigame overlays are styled by HBD's sheet. Temporary: the minigame
# rules move into claw-core/ui/minigame.css and this copy goes away.
cp "$HBD/css/styles.css" "$ROOT/css/core-minigame.css"

# Stage sets read colours from HBD's biome tables, which also carry board copy,
# so they stay in HBD's config. Snapshot just the data the stages need.
NODE_NO_WARNINGS=1 node --input-type=module -e "
import { DISTRICT_BIOMES, HBD_BIOMES } from '$HBD/src/config/GameConfig.js';
const fs = await import('fs');
fs.writeFileSync('$ROOT/src/host/biomes.js',
  '// GENERATED by scripts/sync-core.sh from HundredBlockDash GameConfig. Do not edit.\n' +
  'export const DISTRICT_BIOMES = ' + JSON.stringify(DISTRICT_BIOMES) + ';\n' +
  'export const HBD_BIOMES = ' + JSON.stringify(HBD_BIOMES) + ';\n');
"
echo "synced claw-core from $HBD ($(cd "$HBD" && git rev-parse --short HEAD))"
